/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p playlist_manager xml/org.gnome.Rhythmbox3.PlaylistManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "playlist_manager.h"

/*
 * Implementation of interface class OrgFreedesktopDBusIntrospectableInterface
 *

OrgFreedesktopDBusIntrospectableInterface::OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusIntrospectableInterface::~OrgFreedesktopDBusIntrospectableInterface()
{
}

 *
 * Implementation of interface class OrgFreedesktopDBusPeerInterface
 *

OrgFreedesktopDBusPeerInterface::OrgFreedesktopDBusPeerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPeerInterface::~OrgFreedesktopDBusPeerInterface()
{
}

 *
 * Implementation of interface class OrgFreedesktopDBusPropertiesInterface
 *

OrgFreedesktopDBusPropertiesInterface::OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopDBusPropertiesInterface::~OrgFreedesktopDBusPropertiesInterface()
{
}
*/

/*
 * Implementation of interface class OrgGnomeRhythmbox3PlaylistManagerInterface
 */

OrgGnomeRhythmbox3PlaylistManagerInterface::OrgGnomeRhythmbox3PlaylistManagerInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgGnomeRhythmbox3PlaylistManagerInterface::~OrgGnomeRhythmbox3PlaylistManagerInterface()
{
}

